# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f3a5f567bf53e421ce2a2451ece9f785d48e95d6e0ba0a1e9d41c85312a06d0341095dab57ade77c53a036dc606eb2dd8fd93d61521718fc6fd61e805f7c01c

test:
  secret_key_base: 496b20984680b61830e8b0ecdea372ae30f5f3d4e448269b44668e1c8fab540f1f985b26693b64886d8eb37425fa1963118ed4090fd4d80a055bf1d8558b3387

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
